
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/mnt/1tb/cmake-3.29.0-rc2-linux-x86_64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 6.5.0-21-generic - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/mnt/1tb/cmake-3.29.0-rc2-linux-x86_64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/mnt/1tb/cmake-3.29.0-rc2-linux-x86_64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/mnt/1tb/cmake-3.29.0-rc2-linux-x86_64/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /opt/llvm-18.1.0-rc4/bin/clang 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is Clang, found in:
        /home/upgautam/CLionProjects/FastPathTest/CMakeFiles/3.29.0-rc2/CompilerIdC/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/mnt/1tb/cmake-3.29.0-rc2-linux-x86_64/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:64 (try_compile)"
      - "/mnt/1tb/cmake-3.29.0-rc2-linux-x86_64/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/home/upgautam/CLionProjects/FastPathTest/CMakeFiles/CMakeScratch/TryCompile-4swPdE"
      binary: "/home/upgautam/CLionProjects/FastPathTest/CMakeFiles/CMakeScratch/TryCompile-4swPdE"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/home/upgautam/CLionProjects/FastPathTest/CMakeFiles/CMakeScratch/TryCompile-4swPdE'
        
        Run Build Command(s): /mnt/1tb/cmake-3.29.0-rc2-linux-x86_64/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_40433/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_40433.dir/build.make CMakeFiles/cmTC_40433.dir/build
        gmake[1]: Entering directory '/home/upgautam/CLionProjects/FastPathTest/CMakeFiles/CMakeScratch/TryCompile-4swPdE'
        Building C object CMakeFiles/cmTC_40433.dir/CMakeCCompilerABI.c.o
        /opt/llvm-18.1.0-rc4/bin/clang   -fcolor-diagnostics   -v -MD -MT CMakeFiles/cmTC_40433.dir/CMakeCCompilerABI.c.o -MF CMakeFiles/cmTC_40433.dir/CMakeCCompilerABI.c.o.d -o CMakeFiles/cmTC_40433.dir/CMakeCCompilerABI.c.o -c /mnt/1tb/cmake-3.29.0-rc2-linux-x86_64/share/cmake-3.29/Modules/CMakeCCompilerABI.c
        clang version 18.1.0rc (https://github.com/llvm/llvm-project.git 461274b81d8641eab64d494accddc81d7db8a09e)
        Target: x86_64-unknown-linux-gnu
        Thread model: posix
        InstalledDir: /opt/llvm-18.1.0-rc4/bin
        Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
        Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
        Candidate multilib: .;@m64
        Candidate multilib: 32;@m32
        Candidate multilib: x32;@mx32
        Selected multilib: .;@m64
         (in-process)
         "/opt/llvm-18.1.0-rc4/bin/clang-18" -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -main-file-name CMakeCCompilerABI.c -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=/home/upgautam/CLionProjects/FastPathTest/CMakeFiles/CMakeScratch/TryCompile-4swPdE -v -fcoverage-compilation-dir=/home/upgautam/CLionProjects/FastPathTest/CMakeFiles/CMakeScratch/TryCompile-4swPdE -resource-dir /opt/llvm-18.1.0-rc4/lib/clang/18 -dependency-file CMakeFiles/cmTC_40433.dir/CMakeCCompilerABI.c.o.d -MT CMakeFiles/cmTC_40433.dir/CMakeCCompilerABI.c.o -sys-header-deps -internal-isystem /opt/llvm-18.1.0-rc4/lib/clang/18/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/11/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -ferror-limit 19 -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o CMakeFiles/cmTC_40433.dir/CMakeCCompilerABI.c.o -x c /mnt/1tb/cmake-3.29.0-rc2-linux-x86_64/share/cmake-3.29/Modules/CMakeCCompilerABI.c
        clang -cc1 version 18.1.0rc based upon LLVM 18.1.0rc default target x86_64-unknown-linux-gnu
        ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/11/../../../../x86_64-linux-gnu/include"
        ignoring nonexistent directory "/include"
        #include "..." search starts here:
        #include <...> search starts here:
         /opt/llvm-18.1.0-rc4/lib/clang/18/include
         /usr/local/include
         /usr/include/x86_64-linux-gnu
         /usr/include
        End of search list.
        Linking C executable cmTC_40433
        /mnt/1tb/cmake-3.29.0-rc2-linux-x86_64/bin/cmake -E cmake_link_script CMakeFiles/cmTC_40433.dir/link.txt --verbose=1
        /opt/llvm-18.1.0-rc4/bin/clang  -v -Wl,-v CMakeFiles/cmTC_40433.dir/CMakeCCompilerABI.c.o -o cmTC_40433
        clang version 18.1.0rc (https://github.com/llvm/llvm-project.git 461274b81d8641eab64d494accddc81d7db8a09e)
        Target: x86_64-unknown-linux-gnu
        Thread model: posix
        InstalledDir: /opt/llvm-18.1.0-rc4/bin
        Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
        Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
        Candidate multilib: .;@m64
        Candidate multilib: 32;@m32
        Candidate multilib: x32;@mx32
        Selected multilib: .;@m64
         "/usr/bin/ld" -z relro --hash-style=gnu --eh-frame-hdr -m elf_x86_64 -pie -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o cmTC_40433 /lib/x86_64-linux-gnu/Scrt1.o /lib/x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/11/crtbeginS.o -L/opt/llvm-18.1.0-rc4/bin/../lib/x86_64-unknown-linux-gnu -L/opt/llvm-18.1.0-rc4/lib/clang/18/lib/x86_64-unknown-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/11 -L/usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/lib -L/usr/lib -v CMakeFiles/cmTC_40433.dir/CMakeCCompilerABI.c.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-linux-gnu/11/crtendS.o /lib/x86_64-linux-gnu/crtn.o
        GNU ld (GNU Binutils for Ubuntu) 2.38
        gmake[1]: Leaving directory '/home/upgautam/CLionProjects/FastPathTest/CMakeFiles/CMakeScratch/TryCompile-4swPdE'
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "/mnt/1tb/cmake-3.29.0-rc2-linux-x86_64/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:134 (message)"
      - "/mnt/1tb/cmake-3.29.0-rc2-linux-x86_64/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed C implicit include dir info: rv=done
        found start of include info
        found start of implicit include info
          add: [/opt/llvm-18.1.0-rc4/lib/clang/18/include]
          add: [/usr/local/include]
          add: [/usr/include/x86_64-linux-gnu]
          add: [/usr/include]
        end of search list found
        collapse include dir [/opt/llvm-18.1.0-rc4/lib/clang/18/include] ==> [/opt/llvm-18.1.0-rc4/lib/clang/18/include]
        collapse include dir [/usr/local/include] ==> [/usr/local/include]
        collapse include dir [/usr/include/x86_64-linux-gnu] ==> [/usr/include/x86_64-linux-gnu]
        collapse include dir [/usr/include] ==> [/usr/include]
        implicit include dirs: [/opt/llvm-18.1.0-rc4/lib/clang/18/include;/usr/local/include;/usr/include/x86_64-linux-gnu;/usr/include]
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/mnt/1tb/cmake-3.29.0-rc2-linux-x86_64/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:170 (message)"
      - "/mnt/1tb/cmake-3.29.0-rc2-linux-x86_64/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?))("|,| |$)]
        ignore line: [Change Dir: '/home/upgautam/CLionProjects/FastPathTest/CMakeFiles/CMakeScratch/TryCompile-4swPdE']
        ignore line: []
        ignore line: [Run Build Command(s): /mnt/1tb/cmake-3.29.0-rc2-linux-x86_64/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_40433/fast]
        ignore line: [/usr/bin/gmake  -f CMakeFiles/cmTC_40433.dir/build.make CMakeFiles/cmTC_40433.dir/build]
        ignore line: [gmake[1]: Entering directory '/home/upgautam/CLionProjects/FastPathTest/CMakeFiles/CMakeScratch/TryCompile-4swPdE']
        ignore line: [Building C object CMakeFiles/cmTC_40433.dir/CMakeCCompilerABI.c.o]
        ignore line: [/opt/llvm-18.1.0-rc4/bin/clang   -fcolor-diagnostics   -v -MD -MT CMakeFiles/cmTC_40433.dir/CMakeCCompilerABI.c.o -MF CMakeFiles/cmTC_40433.dir/CMakeCCompilerABI.c.o.d -o CMakeFiles/cmTC_40433.dir/CMakeCCompilerABI.c.o -c /mnt/1tb/cmake-3.29.0-rc2-linux-x86_64/share/cmake-3.29/Modules/CMakeCCompilerABI.c]
        ignore line: [clang version 18.1.0rc (https://github.com/llvm/llvm-project.git 461274b81d8641eab64d494accddc81d7db8a09e)]
        ignore line: [Target: x86_64-unknown-linux-gnu]
        ignore line: [Thread model: posix]
        ignore line: [InstalledDir: /opt/llvm-18.1.0-rc4/bin]
        ignore line: [Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11]
        ignore line: [Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11]
        ignore line: [Candidate multilib: .]
        ignore line: [@m64]
        ignore line: [Candidate multilib: 32]
        ignore line: [@m32]
        ignore line: [Candidate multilib: x32]
        ignore line: [@mx32]
        ignore line: [Selected multilib: .]
        ignore line: [@m64]
        ignore line: [ (in-process)]
        ignore line: [ "/opt/llvm-18.1.0-rc4/bin/clang-18" -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -main-file-name CMakeCCompilerABI.c -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=/home/upgautam/CLionProjects/FastPathTest/CMakeFiles/CMakeScratch/TryCompile-4swPdE -v -fcoverage-compilation-dir=/home/upgautam/CLionProjects/FastPathTest/CMakeFiles/CMakeScratch/TryCompile-4swPdE -resource-dir /opt/llvm-18.1.0-rc4/lib/clang/18 -dependency-file CMakeFiles/cmTC_40433.dir/CMakeCCompilerABI.c.o.d -MT CMakeFiles/cmTC_40433.dir/CMakeCCompilerABI.c.o -sys-header-deps -internal-isystem /opt/llvm-18.1.0-rc4/lib/clang/18/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/11/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -ferror-limit 19 -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o CMakeFiles/cmTC_40433.dir/CMakeCCompilerABI.c.o -x c /mnt/1tb/cmake-3.29.0-rc2-linux-x86_64/share/cmake-3.29/Modules/CMakeCCompilerABI.c]
        ignore line: [clang -cc1 version 18.1.0rc based upon LLVM 18.1.0rc default target x86_64-unknown-linux-gnu]
        ignore line: [ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/11/../../../../x86_64-linux-gnu/include"]
        ignore line: [ignoring nonexistent directory "/include"]
        ignore line: [#include "..." search starts here:]
        ignore line: [#include <...> search starts here:]
        ignore line: [ /opt/llvm-18.1.0-rc4/lib/clang/18/include]
        ignore line: [ /usr/local/include]
        ignore line: [ /usr/include/x86_64-linux-gnu]
        ignore line: [ /usr/include]
        ignore line: [End of search list.]
        ignore line: [Linking C executable cmTC_40433]
        ignore line: [/mnt/1tb/cmake-3.29.0-rc2-linux-x86_64/bin/cmake -E cmake_link_script CMakeFiles/cmTC_40433.dir/link.txt --verbose=1]
        ignore line: [/opt/llvm-18.1.0-rc4/bin/clang  -v -Wl -v CMakeFiles/cmTC_40433.dir/CMakeCCompilerABI.c.o -o cmTC_40433]
        ignore line: [clang version 18.1.0rc (https://github.com/llvm/llvm-project.git 461274b81d8641eab64d494accddc81d7db8a09e)]
        ignore line: [Target: x86_64-unknown-linux-gnu]
        ignore line: [Thread model: posix]
        ignore line: [InstalledDir: /opt/llvm-18.1.0-rc4/bin]
        ignore line: [Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11]
        ignore line: [Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11]
        ignore line: [Candidate multilib: .]
        ignore line: [@m64]
        ignore line: [Candidate multilib: 32]
        ignore line: [@m32]
        ignore line: [Candidate multilib: x32]
        ignore line: [@mx32]
        ignore line: [Selected multilib: .]
        ignore line: [@m64]
        link line: [ "/usr/bin/ld" -z relro --hash-style=gnu --eh-frame-hdr -m elf_x86_64 -pie -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o cmTC_40433 /lib/x86_64-linux-gnu/Scrt1.o /lib/x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/11/crtbeginS.o -L/opt/llvm-18.1.0-rc4/bin/../lib/x86_64-unknown-linux-gnu -L/opt/llvm-18.1.0-rc4/lib/clang/18/lib/x86_64-unknown-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/11 -L/usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/lib -L/usr/lib -v CMakeFiles/cmTC_40433.dir/CMakeCCompilerABI.c.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-linux-gnu/11/crtendS.o /lib/x86_64-linux-gnu/crtn.o]
          arg [/usr/bin/ld] ==> ignore
          arg [-zrelro] ==> ignore
          arg [--hash-style=gnu] ==> ignore
          arg [--eh-frame-hdr] ==> ignore
          arg [-m] ==> ignore
          arg [elf_x86_64] ==> ignore
          arg [-pie] ==> ignore
          arg [-dynamic-linker] ==> ignore
          arg [/lib64/ld-linux-x86-64.so.2] ==> ignore
          arg [-o] ==> ignore
          arg [cmTC_40433] ==> ignore
          arg [/lib/x86_64-linux-gnu/Scrt1.o] ==> obj [/lib/x86_64-linux-gnu/Scrt1.o]
          arg [/lib/x86_64-linux-gnu/crti.o] ==> obj [/lib/x86_64-linux-gnu/crti.o]
          arg [/usr/lib/gcc/x86_64-linux-gnu/11/crtbeginS.o] ==> obj [/usr/lib/gcc/x86_64-linux-gnu/11/crtbeginS.o]
          arg [-L/opt/llvm-18.1.0-rc4/bin/../lib/x86_64-unknown-linux-gnu] ==> dir [/opt/llvm-18.1.0-rc4/bin/../lib/x86_64-unknown-linux-gnu]
          arg [-L/opt/llvm-18.1.0-rc4/lib/clang/18/lib/x86_64-unknown-linux-gnu] ==> dir [/opt/llvm-18.1.0-rc4/lib/clang/18/lib/x86_64-unknown-linux-gnu]
          arg [-L/usr/lib/gcc/x86_64-linux-gnu/11] ==> dir [/usr/lib/gcc/x86_64-linux-gnu/11]
          arg [-L/usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib64] ==> dir [/usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib64]
          arg [-L/lib/x86_64-linux-gnu] ==> dir [/lib/x86_64-linux-gnu]
          arg [-L/lib/../lib64] ==> dir [/lib/../lib64]
          arg [-L/usr/lib/x86_64-linux-gnu] ==> dir [/usr/lib/x86_64-linux-gnu]
          arg [-L/usr/lib/../lib64] ==> dir [/usr/lib/../lib64]
          arg [-L/lib] ==> dir [/lib]
          arg [-L/usr/lib] ==> dir [/usr/lib]
          arg [-v] ==> ignore
          arg [CMakeFiles/cmTC_40433.dir/CMakeCCompilerABI.c.o] ==> ignore
          arg [-lgcc] ==> lib [gcc]
          arg [--as-needed] ==> ignore
          arg [-lgcc_s] ==> lib [gcc_s]
          arg [--no-as-needed] ==> ignore
          arg [-lc] ==> lib [c]
          arg [-lgcc] ==> lib [gcc]
          arg [--as-needed] ==> ignore
          arg [-lgcc_s] ==> lib [gcc_s]
          arg [--no-as-needed] ==> ignore
          arg [/usr/lib/gcc/x86_64-linux-gnu/11/crtendS.o] ==> obj [/usr/lib/gcc/x86_64-linux-gnu/11/crtendS.o]
          arg [/lib/x86_64-linux-gnu/crtn.o] ==> obj [/lib/x86_64-linux-gnu/crtn.o]
        linker tool for 'C': /usr/bin/ld
        collapse library dir [/opt/llvm-18.1.0-rc4/bin/../lib/x86_64-unknown-linux-gnu] ==> [/opt/llvm-18.1.0-rc4/lib/x86_64-unknown-linux-gnu]
        collapse library dir [/opt/llvm-18.1.0-rc4/lib/clang/18/lib/x86_64-unknown-linux-gnu] ==> [/opt/llvm-18.1.0-rc4/lib/clang/18/lib/x86_64-unknown-linux-gnu]
        collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/11] ==> [/usr/lib/gcc/x86_64-linux-gnu/11]
        collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib64] ==> [/usr/lib64]
        collapse library dir [/lib/x86_64-linux-gnu] ==> [/lib/x86_64-linux-gnu]
        collapse library dir [/lib/../lib64] ==> [/lib64]
        collapse library dir [/usr/lib/x86_64-linux-gnu] ==> [/usr/lib/x86_64-linux-gnu]
        collapse library dir [/usr/lib/../lib64] ==> [/usr/lib64]
        collapse library dir [/lib] ==> [/lib]
        collapse library dir [/usr/lib] ==> [/usr/lib]
        implicit libs: [gcc;gcc_s;c;gcc;gcc_s]
        implicit objs: [/lib/x86_64-linux-gnu/Scrt1.o;/lib/x86_64-linux-gnu/crti.o;/usr/lib/gcc/x86_64-linux-gnu/11/crtbeginS.o;/usr/lib/gcc/x86_64-linux-gnu/11/crtendS.o;/lib/x86_64-linux-gnu/crtn.o]
        implicit dirs: [/opt/llvm-18.1.0-rc4/lib/x86_64-unknown-linux-gnu;/opt/llvm-18.1.0-rc4/lib/clang/18/lib/x86_64-unknown-linux-gnu;/usr/lib/gcc/x86_64-linux-gnu/11;/usr/lib64;/lib/x86_64-linux-gnu;/lib64;/usr/lib/x86_64-linux-gnu;/lib;/usr/lib]
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/mnt/1tb/cmake-3.29.0-rc2-linux-x86_64/share/cmake-3.29/Modules/Internal/CMakeDetermineLinkerId.cmake:40 (message)"
      - "/mnt/1tb/cmake-3.29.0-rc2-linux-x86_64/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:207 (cmake_determine_linker_id)"
      - "/mnt/1tb/cmake-3.29.0-rc2-linux-x86_64/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Running the C compiler's linker: "/usr/bin/ld" "-v"
      GNU ld (GNU Binutils for Ubuntu) 2.38
...
